name: Greeter
on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "Hello"

  lister:
    runs-on: ubuntu-latest
    steps:
      - name: list-files
        run: ls
